### ISSUE TITLE
Update constants

### ISSUE THREAD

**Issue by builder-247** [slothpixel/skyblock-parser#3]
Some constants our out of date, for example list of talisman upgrades.

You can find most of the updated values [here](https://github.com/SkyCryptWebsite/SkyCrypt/tree/master/src/constants).

**Comment by Liopun** [comment]
@builder-247  Can i start working on this?

**Comment by builder-247** [comment]
> @builder-247 Can i start working on this?

Absolutely!

**Comment by builder-247** [comment]
@Liopun Do you still want to work on this?

**Comment by Liopun** [comment]
@builder-247 My bad... I got busy with work! If you want to fix this issue or give it to somebody else, you can go ahead. Other than that, I will have to do it when I get a chance. Thanks!

**Comment by builder-247** [comment]
Closed in https://github.com/slothpixel/skyblock-parser/commit/38e0af34994ae072a5740c544bdebc22b669578d
